baseURL = 'https://mirror4s.github.io/'
languageCode = 'zh-cn'
title = '博客'
theme = 'papermod'
[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'